### ISSUE TITLE
With bind_exporter, DNS will have a sudden increase in parsing time.

### ISSUE THREAD

**Issue by yjlmzh** [prometheus-community/bind_exporter#52] opened 2019-09-25 06:44 UTC
With bind_exporter, DNS will have a sudden increase in parsing time.

the 10000  time  about 6% increase in parsing time

curl http://127.0.0.1:853   The data is about 18m.

One thread CPU of BIND9 is 100%

![image](https://user-images.githubusercontent.com/49852688/65575402-4b262d80-dfa2-11e9-8daf-7fcd31ea525c.png)

**Comment by SuperQ** [comment] 2020-01-06 23:28
This depends on which specific version of bind you have. There are known bugs with bind data output that slows it down.

**Comment by SuperQ** [comment] 2020-01-06 23:31
Duplicate of https://github.com/prometheus-community/bind_exporter/issues/40

**Closed by SuperQ** 2020-01-06 23:31 UTC
