### ISSUE TITLE
exporter Couldn't retrieve BIND stats: failed to unmarshal XML response

### ISSUE THREAD

**Issue by hanyfbj** [prometheus-community/bind_exporter#69] opened 2020-02-27 09:23 UTC
my environment:
BIND 9.12.1-P2 <id:14b0e01>
running on Linux x86_64 3.10.0-693.11.1.el7.x86_64 #1 SMP Mon Dec 4 23:52:40 UTC 2017
built by make with '--prefix=/data/apps/bind' '--with-dlz-mysql=/usr/' '--enable-threads=yes' '--enable-largefile' '--disable-ipv6' '--with-libxml2'
compiled by GCC 4.8.5 20150623 (Red Hat 4.8.5-16)
compiled with OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017
linked to OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017
compiled with libxml2 version: 2.9.1
linked to libxml2 version: 20901
compiled with zlib version: 1.2.7
linked to zlib version: 1.2.7
threads support is enabled

centos(7.4.1708) rpms:
libxml2-devel-2.9.1-6.el7_2.3.x86_64
libxml2-2.9.1-6.el7_2.3.x86_64

exporter logs error:
bind_exporter[24794]: time="2020-02-27T17:14:13+08:00" level=error msg="Couldn't retrieve BIND stats: failed to unmarshal XML response: strconv.ParseInt: parsing \"18446744073709551609\": value out of range" source="bind_exporter.go:405"

bind exporter is running， but not get bind records metric 。
help fix it.

**Comment by SuperQ** [comment] 2020-02-27 13:31
It looks like this might be an incorrect use of int64 where we want uint64 for counters. Can you include a copy of the XML output from your bind server and the version of the bind_exporter you are using?

**Comment by fyunly** [comment] 2020-02-28 02:05
> It looks like this might be an incorrect use of int64 where we want uint64 for counters. Can you include a copy of the XML output from your bind server and the version of the bind_exporter you are using?

xml output file [https://raw.githubusercontent.com/fyunly/bugerror/master/bind_xml_output.txt](url) ,    bind_exporter version 0.3.0 (branch: HEAD, revision: c34ff3d6b4817f42e74b2b05b3797cf99683b4a9)

**Comment by mrizvic** [comment] 2020-12-15 20:43
I have same issue with fresh build. Check it out:

[bind.xml.zip](https://github.com/prometheus-community/bind_exporter/files/5698492/bind.zip)

Also change `node_exporter` to `bind_exporter` 

```
Dec 15 21:23:01 dns-server prometheus[3463528]: level=info ts=2020-12-15T20:23:01.362Z caller=bind_exporter.go:500 msg="Starting node_exporter" version="(version=0.3.0, branch=master, revision=85c1f83bceb928937e64d11e9c44f9b96f5d714d)"                          
Dec 15 21:23:01 dns-server prometheus[3463528]: level=info ts=2020-12-15T20:23:01.362Z caller=bind_exporter.go:501 msg="Build context" build_context="(go=go1.13.15, user=golang@CENTOS8, date=20201207-06:57:37)"                                                   
Dec 15 21:23:01 dns-server prometheus[3463528]: level=info ts=2020-12-15T20:23:01.362Z caller=bind_exporter.go:502 msg="Collectors enabled" collectors=server,view,tasks                               
Dec 15 21:23:01 dns-server prometheus[3463528]: level=info ts=2020-12-15T20:23:01.362Z caller=bind_exporter.go:526 msg="Listening on" address=0.0.0.0:9153
Dec 15 21:23:15 dns-server prometheus[3463528]: level=error ts=2020-12-15T20:23:15.501Z caller=bind_exporter.go:413 msg="Couldn't retrieve BIND stats" err="failed to unmarshal XML response: strconv.ParseInt: parsing \"18446744073709551615\": value out of range"
Dec 15 21:23:30 dns-server prometheus[3463528]: level=error ts=2020-12-15T20:23:30.492Z caller=bind_exporter.go:413 msg="Couldn't retrieve BIND stats" err="failed to unmarshal XML response: strconv.ParseInt: parsing \"18446744073709551615\": value out of range"
Dec 15 21:23:45 dns-server prometheus[3463528]: level=error ts=2020-12-15T20:23:45.497Z caller=bind_exporter.go:413 msg="Couldn't retrieve BIND stats" err="failed to unmarshal XML response: strconv.ParseInt: parsing \"18446744073709551615\": value out of range"
```

**Comment by mrizvic** [comment] 2020-12-15 20:50
Same thing with revision=caf63390312239bd1ee7416417d6896b5a321eed

```
Dec 15 21:49:14 dns-server prometheus[3464738]: level=info ts=2020-12-15T20:49:14.008Z caller=bind_exporter.go:513 msg="Starting bind_exporter" version="(version=0.3.0, branch=master, revision=caf63390312239bd1ee7416417d6896b5a321eed)"
Dec 15 21:49:14 dns-server prometheus[3464738]: level=info ts=2020-12-15T20:49:14.008Z caller=bind_exporter.go:514 msg="Build context" build_context="(go=go1.13.15, user=golang@CENTOS8, date=20201215-20:45:48)"
Dec 15 21:49:14 dns-server prometheus[3464738]: level=info ts=2020-12-15T20:49:14.008Z caller=bind_exporter.go:515 msg="Collectors enabled" collectors=server,view,tasks
Dec 15 21:49:14 dns-server prometheus[3464738]: level=info ts=2020-12-15T20:49:14.009Z caller=bind_exporter.go:539 msg="Listening on" address=0.0.0.0:9153
Dec 15 21:49:15 dns-server prometheus[3464738]: level=error ts=2020-12-15T20:49:15.496Z caller=bind_exporter.go:412 msg="Couldn't retrieve BIND stats" err="failed to unmarshal XML response: strconv.ParseInt: parsing \"18446744073709551602\": value out of range"
```

**Comment by SuperQ** [comment] 2020-12-28 14:36
I think I see what the issue is. The "Gauge" in bind is represented by a uint64, where we have an int64, it's confusing because it's marked as `<counter>` in the XML for view data, but it's actually a gauge.

**Closed** 2021-01-12 13:54 UTC
