### ISSUE TITLE
Cant make on Debian Squeeze

### ISSUE THREAD

**Issue by disklamer** [prometheus-community/bind_exporter#32] opened 2017-07-30 15:05 UTC
dennis@Mango:~/.go/src/github.com/digitalocean/bind_exporter$ make
>> formatting code
>> building binaries
 >   bind_exporter
# github.com/digitalocean/bind_exporter/bind/v2
bind/v2/v2.go:81: cannot convert t (type Counter) to type bind.Counter
bind/v2/v2.go:84: cannot convert t (type Counter) to type bind.Counter
bind/v2/v2.go:87: cannot convert t (type Counter) to type bind.Counter
bind/v2/v2.go:95: cannot convert t (type Counter) to type bind.Counter
bind/v2/v2.go:98: cannot convert t (type Counter) to type bind.Counter
!! command failed: build -o /home/dennis/.go/src/github.com/digitalocean/bind_exporter/bind_exporter -ldflags -X github.com/digitalocean/bind_exporter/vendor/github.com/prometheus/common/version.Version=0.2.0-dev -X github.com/digitalocean/bind_exporter/vendor/github.com/prometheus/common/version.Revision=dae68f9a72da14e080aea554b7d4f1495904ba1a -X github.com/digitalocean/bind_exporter/vendor/github.com/prometheus/common/version.Branch=master -X github.com/digitalocean/bind_exporter/vendor/github.com/prometheus/common/version.BuildUser=dennis@Mango -X github.com/digitalocean/bind_exporter/vendor/github.com/prometheus/common/version.BuildDate=20170730-15:05:10  -extldflags '-static' github.com/digitalocean/bind_exporter: exit status 2
Makefile:43: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by grobie** [comment] 2017-07-31 08:34
I can't reproduce this issue in go1.8.3. What golang version do you use (`go version`)?

**Comment by mattsdni** [comment] 2017-08-03 15:36
I was able to reproduce with go version 1.6.3.
Updating to go version 1.8.3 fixed the issue.
Testing was done on amazon linux 4.4.19-29.55.amzn1.x86_64

**Comment by mdebord1** [comment] 2018-04-29 00:58
Exact same build issue `cannot convert t (type Counter) to type bind.Counter` on Ubuntu 16.04 w/ bind_exporter v0.2.0

Pre-compiled release binary also doesn't work on Ubuntu 16 :( -- Same binary works on my Mac. Seems to be very non-Debian friendly.

**Comment by TheTincho** [comment] 2018-10-22 22:01
FYI, Debian offers a package for bind_exporter in the official repos: https://packages.debian.org/sid/prometheus-bind-exporter

**Comment by anarcat** [comment] 2019-09-16 19:23
squeeze is really, really old by now. i don't think we should try to support it and this should be closed.

**Comment by SuperQ** [comment] 2020-01-06 23:35
This should be fixed by the latest build updates.

**Closed by SuperQ** 2020-01-06 23:35 UTC
